checks:
  method-complexity:
    enabled: true
    config:
      threshold: 50
  method-lines:
    enabled: true
    config:
      threshold: 200
  file-lines:
    enabled: true
    config:
      threshold: 800
exclude_patterns:
- "test/"
- "**/.eslintrc.cjs"
- "**/babel.config.cjs"