export default {
  vec2: 'vec2',
  vec3: 'vec3',
  vec4: 'vec4',
  mat2: 'mat2',
  mat2d: 'mat2d',
  mat3: 'mat3',
  mat4: 'mat4',
  quat: 'quat',
  quat2: 'quat2',

  'vec2.create': 'vec2',
  'vec2.clone': 'vec2',
  'vec2.fromValues': 'vec2',
  'vec2.copy': 'vec2',
  'vec2.set': 'vec2',
  'vec2.add': 'vec2',
  'vec2.subtract': 'vec2',
  'vec2.multiply': 'vec2',
  'vec2.divide': 'vec2',
  'vec2.ceil': 'vec2',
  'vec2.floor': 'vec2',
  'vec2.min': 'vec2',
  'vec2.max': 'vec2',
  'vec2.round': 'vec2',
  'vec2.scale': 'vec2',
  'vec2.scaleAndAdd': 'vec2',
  // 'vec2.distance': 'number',
  // 'vec2.squaredDistance': 'number',
  // 'vec2.length': 'number',
  // 'vec2.squaredLength': 'number',
  'vec2.negate': 'vec2',
  'vec2.inverse': 'vec2',
  'vec2.normalize': 'vec2',
  // 'vec2.dot': 'number',
  'vec2.cross': 'vec3',
  'vec2.lerp': 'vec2',
  'vec2.random': 'vec2',
  'vec2.transformMat2': 'vec2',
  'vec2.transformMat2d': 'vec2',
  'vec2.transformMat3': 'vec2',
  'vec2.transformMat4': 'vec2',
  'vec2.rotate': 'vec2',
  // 'vec2.angle': 'number',
  'vec2.zero': 'vec2',
  // 'vec2.str': 'string',
  // 'vec2.exactEquals': 'boolean',
  // 'vec2.equals': 'boolean',
  // 'vec2.len': 'number',
  'vec2.sub': 'vec2',
  'vec2.mul': 'vec2',
  'vec2.div': 'vec2',
  // 'vec2.dist': 'number',
  // 'vec2.sqrDist': 'number',
  // 'vec2.sqrLen': 'number',
  // 'vec2.forEach': 'array',

  'vec3.create': 'vec3',
  'vec3.clone': 'vec3',
  'vec3.fromValues': 'vec3',
  'vec3.copy': 'vec3',
  'vec3.set': 'vec3',
  'vec3.add': 'vec3',
  'vec3.subtract': 'vec3',
  'vec3.multiply': 'vec3',
  'vec3.divide': 'vec3',
  'vec3.ceil': 'vec3',
  'vec3.floor': 'vec3',
  'vec3.min': 'vec3',
  'vec3.max': 'vec3',
  'vec3.round': 'vec3',
  'vec3.scale': 'vec3',
  'vec3.scaleAndAdd': 'vec3',
  // 'vec3.distance': 'number',
  // 'vec3.squaredDistance': 'number',
  // 'vec3.length': 'number',
  // 'vec3.squaredLength': 'number',
  'vec3.negate': 'vec3',
  'vec3.inverse': 'vec3',
  'vec3.normalize': 'vec3',
  // 'vec3.dot': 'number',
  'vec3.cross': 'vec3',
  'vec3.lerp': 'vec3',
  'vec3.hermite': 'vec3',
  'vec3.bezier': 'vec3',
  'vec3.random': 'vec3',
  'vec3.transformMat3': 'vec3',
  'vec3.transformMat4': 'vec3',
  'vec3.transformQuat': 'vec3',
  'vec3.rotateX': 'vec3',
  'vec3.rotateY': 'vec3',
  'vec3.rotateZ': 'vec3',
  // 'vec3.angle': 'number',
  'vec3.zero': 'vec3',
  // 'vec3.str': 'string',
  // 'vec3.exactEquals': 'boolean',
  // 'vec3.equals': 'boolean',
  // 'vec3.len': 'number',
  'vec3.sub': 'vec3',
  'vec3.mul': 'vec3',
  'vec3.div': 'vec3',
  // 'vec3.dist': 'number',
  // 'vec3.sqrDist': 'number',
  // 'vec3.sqrLen': 'number',
  // 'vec3.forEach': 'array',

  'vec4.create': 'vec4',
  'vec4.clone': 'vec4',
  'vec4.fromValues': 'vec4',
  'vec4.copy': 'vec4',
  'vec4.set': 'vec4',
  'vec4.add': 'vec4',
  'vec4.subtract': 'vec4',
  'vec4.multiply': 'vec4',
  'vec4.divide': 'vec4',
  'vec4.ceil': 'vec4',
  'vec4.floor': 'vec4',
  'vec4.min': 'vec4',
  'vec4.max': 'vec4',
  'vec4.round': 'vec4',
  'vec4.scale': 'vec4',
  'vec4.scaleAndAdd': 'vec4',
  // 'vec4.distance': 'number',
  // 'vec4.squaredDistance': 'number',
  // 'vec4.length': 'number',
  // 'vec4.squaredLength': 'number',
  'vec4.negate': 'vec4',
  'vec4.inverse': 'vec4',
  'vec4.normalize': 'vec4',
  // 'vec4.dot': 'number',
  'vec4.cross': 'vec4',
  'vec4.lerp': 'vec4',
  'vec4.random': 'vec4',
  'vec4.transformMat4': 'vec4',
  'vec4.transformQuat': 'vec4',
  'vec4.zero': 'vec4',
  // 'vec4.str': 'string',
  // 'vec4.exactEquals': 'boolean',
  // 'vec4.equals': 'boolean',
  // 'vec4.len': 'number',
  'vec4.sub': 'vec4',
  'vec4.mul': 'vec4',
  'vec4.div': 'vec4',
  // 'vec4.dist': 'number',
  // 'vec4.sqrDist': 'number',
  // 'vec4.sqrLen': 'number',
  // 'vec4.forEach': 'array',

  'mat2.create': 'mat2',
  'mat2.clone': 'mat2',
  'mat2.copy': 'mat2',
  'mat2.identity': 'mat2',
  'mat2.fromValues': 'mat2',
  'mat2.set': 'mat2',
  'mat2.transpose': 'mat2',
  'mat2.invert': 'mat2',
  'mat2.adjoint': 'mat2',
  // 'mat2.determinant': 'number',
  'mat2.multiply': 'mat2',
  'mat2.rotate': 'mat2',
  'mat2.scale': 'mat2',
  'mat2.fromRotation': 'mat2',
  'mat2.fromScaling': 'mat2',
  // 'mat2.str': 'string',
  // 'mat2.frob': 'number',
  'mat2.add': 'mat2',
  'mat2.subtract': 'mat2',
  // 'mat2.exactEquals': 'boolean',
  // 'mat2.equals': 'boolean',
  'mat2.multiplyScalar': 'mat2',
  'mat2.multiplyScalarAndAdd': 'mat2',
  'mat2.mul': 'mat2',
  'mat2.sub': 'mat2',

  'mat2d.create': 'mat2d',
  'mat2d.clone': 'mat2d',
  'mat2d.copy': 'mat2d',
  'mat2d.identity': 'mat2d',
  'mat2d.fromValues': 'mat2d',
  'mat2d.set': 'mat2d',
  'mat2d.invert': 'mat2d',
  // 'mat2d.determinant': 'number',
  'mat2d.multiply': 'mat2d',
  'mat2d.rotate': 'mat2d',
  'mat2d.scale': 'mat2d',
  'mat2d.translate': 'mat2d',
  'mat2d.fromRotation': 'mat2d',
  'mat2d.fromScaling': 'mat2d',
  'mat2d.fromTranslation': 'mat2d',
  // 'mat2d.str': 'string',
  // 'mat2d.frob': 'number',
  'mat2d.add': 'mat2d',
  'mat2d.subtract': 'mat2d',
  'mat2d.multiplyScalar': 'mat2d',
  'mat2d.multiplyScalarAndAdd': 'mat2d',
  // 'mat2d.exactEquals': 'boolean',
  // 'mat2d.equals': 'boolean',
  'mat2d.mul': 'mat2d',
  'mat2d.sub': 'mat2d',

  'mat3.create': 'mat3',
  'mat3.fromMat4': 'mat3',
  'mat3.clone': 'mat3',
  'mat3.copy': 'mat3',
  'mat3.fromValues': 'mat3',
  'mat3.set': 'mat3',
  'mat3.identity': 'mat3',
  'mat3.transpose': 'mat3',
  'mat3.invert': 'mat3',
  'mat3.adjoint': 'mat3',
  // 'mat3.determinant': 'number',
  'mat3.multiply': 'mat3',
  'mat3.translate': 'mat3',
  'mat3.rotate': 'mat3',
  'mat3.scale': 'mat3',
  'mat3.fromTranslation': 'mat3',
  'mat3.fromRotation': 'mat3',
  'mat3.fromScaling': 'mat3',
  'mat3.fromMat2d': 'mat3',
  'mat3.fromQuat': 'mat3',
  'mat3.normalFromMat4': 'mat3',
  'mat3.projection': 'mat3',
  // 'mat3.str': 'string',
  // 'mat3.frob': 'number',
  'mat3.add': 'mat3',
  'mat3.subtract': 'mat3',
  'mat3.multiplyScalar': 'mat3',
  'mat3.multiplyScalarAndAdd': 'mat3',
  // 'mat3.exactEquals': 'boolean',
  // 'mat3.equals': 'boolean',
  'mat3.mul': 'mat3',
  'mat3.sub': 'mat3',

  'mat4.create': 'mat4',
  'mat4.clone': 'mat4',
  'mat4.copy': 'mat4',
  'mat4.fromValues': 'mat4',
  'mat4.set': 'mat4',
  'mat4.identity': 'mat4',
  'mat4.transpose': 'mat4',
  'mat4.invert': 'mat4',
  'mat4.adjoint': 'mat4',
  // 'mat4.determinant': 'number',
  'mat4.multiply': 'mat4',
  'mat4.translate': 'mat4',
  'mat4.scale': 'mat4',
  'mat4.rotate': 'mat4',
  'mat4.rotateX': 'mat4',
  'mat4.rotateY': 'mat4',
  'mat4.rotateZ': 'mat4',
  'mat4.fromTranslation': 'mat4',
  'mat4.fromScaling': 'mat4',
  'mat4.fromRotation': 'mat4',
  'mat4.fromXRotation': 'mat4',
  'mat4.fromYRotation': 'mat4',
  'mat4.fromZRotation': 'mat4',
  'mat4.fromRotationTranslation': 'mat4',
  'mat4.fromQuat2': 'mat4',
  'mat4.getTranslation': 'vec3',
  'mat4.getScaling': 'vec3',
  'mat4.getRotation': 'quat',
  'mat4.decompose': 'quat',
  'mat4.fromRotationTranslationScale': 'mat4',
  'mat4.fromRotationTranslationScaleOrigin': 'mat4',
  'mat4.fromQuat': 'mat4',
  'mat4.frustum': 'mat4',
  'mat4.perspectiveN0': 'mat4',
  'mat4.perspectiveZ0': 'mat4',
  'mat4.perspectiveFromFieldOfView': 'mat4',
  'mat4.orthoNO': 'mat4',
  'mat4.orthoZO': 'mat4',
  'mat4.lookAt': 'mat4',
  'mat4.targetTo': 'mat4',
  // 'mat4.str': 'string',
  // 'mat4.frob': 'number',
  'mat4.add': 'mat4',
  'mat4.subtract': 'mat4',
  'mat4.multiplyScalar': 'mat4',
  'mat4.multiplyScalarAndAdd': 'mat4',
  // 'mat4.exactEquals': 'boolean',
  // 'mat4.equals': 'boolean',
  'mat4.mul': 'mat4',
  'mat4.sub': 'mat4',

  'quat.create': 'quat',
  'quat.identity': 'quat',
  'quat.setAxisAngle': 'quat',
  'quat.getAxisAngle': 'vec3',
  // 'quat.getAngle': 'number',
  'quat.multiply': 'quat',
  'quat.rotateX': 'quat',
  'quat.rotateY': 'quat',
  'quat.rotateZ': 'quat',
  'quat.calculateW': 'quat',
  'quat.exp': 'quat',
  'quat.ln': 'quat',
  'quat.pow': 'quat',
  'quat.slerp': 'quat',
  'quat.random': 'quat',
  'quat.invert': 'quat',
  'quat.conjugate': 'quat',
  'quat.fromMat3': 'quat',
  'quat.fromEuler': 'quat',
  // 'quat.str': 'string',
  'quat.clone': 'quat',
  'quat.fromValues': 'quat',
  'quat.copy': 'quat',
  'quat.set': 'quat',
  'quat.add': 'quat',
  'quat.mul': 'quat',
  'quat.scale': 'quat',
  'quat.dot': 'quat',
  'quat.lerp': 'quat',
  'quat.length': 'quat',
  'quat.squaredLength': 'quat',
  'quat.sqrLen': 'quat',
  'quat.normalize': 'quat',
  // 'quat.exactEquals': 'boolean',
  // 'quat.equals': 'boolean',
  'quat.rotationTo': 'quat',
  'quat.sqlerp': 'quat',
  'quat.setAxes': 'quat',

  'quat2.create': 'quat2',
  'quat2.clone': 'quat2',
  'quat2.fromValues': 'quat2',
  'quat2.fromRotationTranslationValues': 'quat2',
  'quat2.fromRotationTranslation': 'quat2',
  'quat2.fromTranslation': 'quat2',
  'quat2.fromRotation': 'quat2',
  'quat2.fromMat4': 'quat2',
  'quat2.copy': 'quat2',
  'quat2.identity': 'quat2',
  'quat2.set': 'quat2',
  'quat2.getDual': 'quat',
  'quat2.setReal': 'quat2',
  'quat2.setDual': 'quat2',
  'quat2.getTranslation': 'vec3',
  'quat2.translate': 'quat2',
  'quat2.rotateX': 'quat2',
  'quat2.rotateY': 'quat2',
  'quat2.rotateZ': 'quat2',
  'quat2.rotateByQuatAppend': 'quat2',
  'quat2.rotateByQuatPrepend': 'quat2',
  'quat2.rotateAroundAxis': 'quat2',
  'quat2.add': 'quat2',
  'quat2.multiply': 'quat2',
  'quat2.mul': 'quat2',
  'quat2.scale': 'quat2',
  // 'quat2.dot': 'number',
  'quat2.lerp': 'quat2',
  'quat2.invert': 'quat2',
  'quat2.conjugate': 'quat2',
  // 'quat2.length': 'number',
  // 'quat2.len': 'number',
  // 'quat2.squaredLength': 'number',
  // 'quat2.sqrLen': 'number',
  'quat2.normalize': 'quat2',
  'quat2.str': 'quat2',
  // 'quat2.exactEquals': 'boolean',
  // 'quat2.equals': 'boolean',
};
