module.exports = {
  'vec2.distance': 'number',
  'vec2.squaredDistance': 'number',
  'vec2.length': 'number',
  'vec2.squaredLength': 'number',
  'vec2.dot': 'number',
  'vec2.cross': 'vec3',
  'vec2.angle': 'number',
  'vec2.str': 'string',
  'vec2.exactEquals': 'boolean',
  'vec2.equals': 'boolean',
  'vec2.len': 'number',
  'vec2.dist': 'number',
  'vec2.sqrDist': 'number',
  'vec2.sqrLen': 'number',
  'vec2.forEach': 'array',

  'vec3.distance': 'number',
  'vec3.squaredDistance': 'number',
  'vec3.length': 'number',
  'vec3.squaredLength': 'number',
  'vec3.dot': 'number',
  'vec3.angle': 'number',
  'vec3.str': 'string',
  'vec3.exactEquals': 'boolean',
  'vec3.equals': 'boolean',
  'vec3.len': 'number',
  'vec3.dist': 'number',
  'vec3.sqrDist': 'number',
  'vec3.sqrLen': 'number',
  'vec3.forEach': 'array',

  'vec4.distance': 'number',
  'vec4.squaredDistance': 'number',
  'vec4.length': 'number',
  'vec4.squaredLength': 'number',
  'vec4.dot': 'number',
  'vec4.angle': 'number',
  'vec4.str': 'string',
  'vec4.exactEquals': 'boolean',
  'vec4.equals': 'boolean',
  'vec4.len': 'number',
  'vec4.dist': 'number',
  'vec4.sqrDist': 'number',
  'vec4.sqrLen': 'number',
  'vec4.forEach': 'array',

  'mat2.determinant': 'number',
  'mat2.str': 'string',
  'mat2.frob': 'number',
  'mat2.exactEquals': 'boolean',
  'mat2.equals': 'boolean',

  'mat2d.determinant': 'number',
  'mat2d.str': 'string',
  'mat2d.frob': 'number',
  'mat2d.exactEquals': 'boolean',
  'mat2d.equals': 'boolean',

  'mat3.determinant': 'number',
  'mat3.str': 'string',
  'mat3.frob': 'number',
  'mat3.exactEquals': 'boolean',
  'mat3.equals': 'boolean',

  'mat4.determinant': 'number',
  'mat4.str': 'string',
  'mat4.frob': 'number',
  'mat4.exactEquals': 'boolean',
  'mat4.equals': 'boolean',
};